### ISSUE TITLE
Fix protection of hySpc.testthat 

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.testthat#10]
Branch `develop` in https://github.com/r-hyperspec/hySpc.testthat is protected. But the status of `pkgdown` condition newer arrives so it is impossible to commit to that branch. @cbeleites, please, fix this by chosing more appropriate (or removing) conditions.

![image](https://user-images.githubusercontent.com/12725868/90075854-12508d80-dd07-11ea-9d43-01b1ab7e71d6.png)

**Comment by cbeleites** [comment]
Done
