### ISSUE TITLE
GH Actions pkgdown: separate installation and roxygenation steps

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.testthat#2]
Maybe it is better to move these lines to the installation step:
https://github.com/r-hyperspec/hySpc.testthat/blob/e7633b7eb92fcb2573d0ac25abf160fc8eb5e5be/.github/workflows/pkgdown.yaml#L42
and in the `Roxygenize` use only `devtools::document()`. In case of error, it would be more apparent, which step (installation or roxygenation) fails.

**Comment by GegznaV** [comment]
I think this fix should also go to package skeleton repo https://github.com/eoduniyi/hySpc.skeleton

**Comment by cbeleites** [comment]
Yes, together with several others. I'll submit them to the skeleton package once **hySpc.testthat** builds correctly under Travis as well. (gh-pages are now working and actually appear in the web as they are supposed to)
