### ISSUE TITLE
How to use hySpc.testthat correctly in hypSpc* series. 

### ISSUE THREAD

**Issue by eoduniyi** [r-hyperspec/hySpc.testthat#3]
I am having a little trouble understanding how to apply the `hySpc.testthat` package in the `hySpc*` series. For example, deriving the `hySpc.read.Witec` package from the skeleton I find the following folders and files:

```
└── tests
    ├── testthat
    │   └── test_attached.R
    └── testthat.R
```

In those files there is code that is supposed to be updated with the packages information:

**testthat.R**
```R
library(hySpc.testthat)
library(hySpc.read.Witec)
test_check("hySpc.read.Witec")
```

**test_attached.R**
```R
# run all tests attached to objects
hySpc.testthat::unittest("hySpc.read.Witec")
```

...oh I just need to have a file called unittest.R, which can be empty. I guess the main point is to just run `devtools::test()` to check test, then install -> document -> check. Then, the point of the `hySpc.testthat` the package must be to reduce the code footprint of the unittest.R file and the testthat.R file. Interesting...so, we're just not moving the same pieces of code from one package to the other in case of breaking changes.

**Comment by cbeleites** [comment]
No, we shouldn't need to have a file unittest.R, but since we had it at some point, it needs to be removed from the Collate field in DESCRIPTION. `document()` should do that - if it works as it should.

**Comment by eoduniyi** [comment]
Okay, I think I understand the functionality of `hySpc.testthat` going to close #3 now
